apiVersion: v1
kind: Service
metadata:
    name: "testingdeploymentcenter-ba41"
    labels:
        app: "testingdeploymentcenter-ba41"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testingdeploymentcenter-ba41"