name: setup kubectl test
on:
    workflow_dispatch: {}

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.25.5
      - run: kubectl version
